POST http://localhost/api/orders
Content-Type: application/json
Accept: application/json

{
    "name": "Johnny Silverhand",
    "email": "arasaki@hater.com",
    "shipping_type": "COURIER_SHIPPING",
    "shipping_name": "Test John",
    "shipping_postcode": "1234",
    "shipping_city": "Night City",
    "shipping_address": "Street 1",
    "billing_name": "Test John",
    "billing_postcode": "1234",
    "billing_city": "Night City",
    "billing_address": "Street 2",
    "order_products": [
        {
            "name": "Gun",
            "price": 4000,
            "quantity": 4
        },
        {
            "name": "medpack",
            "price": 300,
            "quantity": 10
        }
    ]
}

###

POST http://localhost/api/order/9a687816-4497-44ac-b544-a97f3c4212d9/status
Content-Type: application/json
Accept: application/json

{
    "status": "FULLFILLED"
}

###

POST http://localhost/api/orders/list
Content-Type: application/json
Accept: application/json

{
    "status": "FULLFILLED",
    "created_after": "2010-01-01",
    "created_before": "2025-01-01"
}
